"""Upgrade posts table1

Revision ID: ddee51d1fb1c
Revises: 7d92158a75c3
Create Date: 2025-01-23 17:30:24.059113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddee51d1fb1c'
down_revision = '7d92158a75c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.create_foreign_key('fk_posts_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_posts_user_id_users', type_='foreignkey')
        batch_op.alter_column('category',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
